DROP TABLE TB_TOP_STORE;
CREATE TABLE TB_TOP_STORE (
    SEQ int (11) NOT NULL AUTO_INCREMENT,
    DRW_NO int(11) NOT NULL,
    STORE_CODE VARCHAR(12) NOT NULL,
    STORE_NAME VARCHAR(40),
    ADDR VARCHAR(120),
    LAT VARCHAR(14),
    LON VARCHAR(14),
    TEL_NO VARCHAR(20),
    PRIMARY KEY(SEQ)
);